### ISSUE TITLE
license for Karotten Chess unknown

### ISSUE THREAD

**Issue by yellow-panther** [Highhand/Karotten#2]
Somebody created a binary for win32 and x64 operation systems, but generally it is important to know under which kind of license the source code was publicly released/modified.

cf. https://opensource.org/licenses

By the way: would it be o.k. for you that a public download link of Windows binaries is available e.g. on CCWiki http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:chess_engine_list ?
Actually cf. section "Source Code Only List" - http://www.rwbc-chess.de/ is another possibility to mention WB/UCI compatible chess engines

**Comment by simka275** [comment]
I don't know if I consider this chess-engine publicly released (yet). It is still in the development phase, since their are some bugs with move generations I haven't found yet. I also have way to little knowledge about licenses to license this code in anyway. But if you want to compile the code and link to the binaries feel free to do so.

**Comment by yellow-panther** [comment]
http://talkchess.com/forum/viewtopic.php?topic_view=threads&p=746243&t=66229
- cf. these links for details

2018-01-14 14:52 GMT+01:00 Simon Karlsson <notifications@github.com>:
